-- Migration: Create Businesses table
-- Description: Stores business information and integration details (generalized from Restaurants)

CREATE TABLE IF NOT EXISTS Businesses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address TEXT,
    phone_number VARCHAR(20),
    twilio_phone_number VARCHAR(20),
    twilio_details JSON COMMENT 'Twilio configuration and settings',
    deepgram_details JSON COMMENT 'Deepgram configuration and settings',
    forward_minutes INT DEFAULT 0 COMMENT 'Forward booking window in minutes',
    backward_minutes INT DEFAULT 0 COMMENT 'Backward booking window in minutes',
    is_credit_card_required_for_reservation BOOLEAN DEFAULT FALSE,
    forward_escalations BOOLEAN DEFAULT FALSE,
    escalation_phone_number VARCHAR(20) NULL,
    timezone VARCHAR(64) DEFAULT 'America/Vancouver',
    reservation_seating_capacity INT DEFAULT 50,
    reservation_advance_days INT DEFAULT 30,
    kill_switch_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    -- Daily operating hours (per-day open/close/closed for 7 days)
    monday_open TIME NULL,
    monday_close TIME NULL,
    monday_closed BOOLEAN DEFAULT FALSE,
    tuesday_open TIME NULL,
    tuesday_close TIME NULL,
    tuesday_closed BOOLEAN DEFAULT FALSE,
    wednesday_open TIME NULL,
    wednesday_close TIME NULL,
    wednesday_closed BOOLEAN DEFAULT FALSE,
    thursday_open TIME NULL,
    thursday_close TIME NULL,
    thursday_closed BOOLEAN DEFAULT FALSE,
    friday_open TIME NULL,
    friday_close TIME NULL,
    friday_closed BOOLEAN DEFAULT FALSE,
    saturday_open TIME NULL,
    saturday_close TIME NULL,
    saturday_closed BOOLEAN DEFAULT FALSE,
    sunday_open TIME NULL,
    sunday_close TIME NULL,
    sunday_closed BOOLEAN DEFAULT FALSE,
    -- 24-hour flags for each day
    monday_24_hours BOOLEAN DEFAULT FALSE,
    tuesday_24_hours BOOLEAN DEFAULT FALSE,
    wednesday_24_hours BOOLEAN DEFAULT FALSE,
    thursday_24_hours BOOLEAN DEFAULT FALSE,
    friday_24_hours BOOLEAN DEFAULT FALSE,
    saturday_24_hours BOOLEAN DEFAULT FALSE,
    sunday_24_hours BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_name (name),
    INDEX idx_phone_number (phone_number),
    INDEX idx_twilio_phone_number (twilio_phone_number),
    INDEX idx_created_at (created_at),
    INDEX idx_reservation_capacity_config (reservation_seating_capacity, reservation_advance_days)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
